let fecha = new Date(1945,10,4)
fecha = new Date(1954475347853)
console.log(fecha)
console.log(fecha.toString())
console.log(fecha.toDateString())
console.log(fecha.toISOString())
console.log(fecha.toGMTString())

console.log(fecha.getFullYear())
console.log(fecha.getDate())
console.log(new Date().getDay())